### ISSUE TITLE
Group json schema moved and changed to RAML

### ISSUE THREAD

**Issue by shinka81** [dcos-labs/marathon-validate#1]
Hi @tobilg,

Thanks for this neat little tool, very handy. I noticed that the group type validation wasn't working so I dug in to what all changed. It looks like the Group json schema was removed from marathon at some point in favor of RAML type definition. I decided to see if I could get [this](https://github.com/raml-org/ramldt2jsonschema) library to work by parsing the group.raml but it is throwing `RangeError: Maximum call stack size exceeded` unless I increase my local stack size. Even after that it gets a segmentation fault error but I stopped digging in to it at that point. I will most likely open an issue with that team to dig deeper in to it. 

Anyways, just wanted to let others know incase they run in to this as well. cheers.

**Comment by tobilg** [comment]
Thanks for reporting @shinka81 I'll have a look.

**Comment by tobilg** [comment]
I opened an issue about the missing file with the Marathon project: https://github.com/mesosphere/marathon/issues/4643 

We'll see what the answer is @shinka81

**Comment by tobilg** [comment]
The group.json will be added again, as of the Marathon team's comment under https://github.com/mesosphere/marathon/issues/4643. I'll closed this issue once it lands.

**Comment by tobilg** [comment]
The group.json was added again with https://github.com/mesosphere/marathon/commit/8fda479929e4a01a1557da35f4c909161ef5da26 I think this means that with the next release version, the group.json will be usable again.
